/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type AboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type CustomEvent = {
  _id: string;
  _type: 'customEvent';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  name?: string;
  status?: 'inProgress' | 'approved';
  description?: string;
  startDate?: string;
  endDate?: string;
  type?: 'internal' | 'external';
  categories?: Array<'Marketing' | 'Development'>;
};

export type CustomEventReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'customEvent';
};

export type TablePage = {
  _id: string;
  _type: 'tablePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  h1?: string;
  tableData?: Array<
    {
      _key: string;
    } & CustomEventReference
  >;
};

export type CardInfoReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'cardInfo';
};

export type CardsPage = {
  _id: string;
  _type: 'cardsPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  h1?: string;
  subText?: string;
  infoCards?: Array<
    {
      _key: string;
    } & CardInfoReference
  >;
};

export type CardInfo = {
  _id: string;
  _type: 'cardInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  name?: string;
  shortDescription?: string;
  amount?: number;
  rating?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ProjectInfo = {
  _id: string;
  _type: 'projectInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projectName?: string;
  link?: string;
  projectDescription?: string;
  projectLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  techs?: Array<string>;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ProjectInfoReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'projectInfo';
};

export type DashboardPage = {
  _id: string;
  _type: 'dashboardPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  h1?: string;
  subText?: string;
  detailInfo?: Array<string>;
  cardsTitle?: string;
  cards?: Array<
    {
      _key: string;
    } & ProjectInfoReference
  >;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  welcomeText?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AboutPage
  | Slug
  | CustomEvent
  | CustomEventReference
  | TablePage
  | CardInfoReference
  | CardsPage
  | CardInfo
  | SanityImageAssetReference
  | ProjectInfo
  | SanityImageCrop
  | SanityImageHotspot
  | ProjectInfoReference
  | DashboardPage
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/src/app/(app-home)/about/page.tsx
// Variable: getAboutPageContent
// Query: *[_type=="aboutPage"][0]{content}
export type GetAboutPageContentResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type=="aboutPage"][0]{\ncontent\n}': GetAboutPageContentResult;
  }
}
