/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CatImageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'catImage';
};

export type GalleryPage = {
  _id: string;
  _type: 'galleryPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  catImages?: Array<
    {
      _key: string;
    } & CatImageReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type CatImage = {
  _id: string;
  _type: 'catImage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  name?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ContactPage = {
  _id: string;
  _type: 'contactPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type AboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type CustomEvent = {
  _id: string;
  _type: 'customEvent';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  name?: string;
  status?: 'inProgress' | 'approved';
  description?: string;
  startDate?: string;
  endDate?: string;
  type?: 'internal' | 'external';
  categories?: Array<'Marketing' | 'Development'>;
};

export type CustomEventReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'customEvent';
};

export type TablePage = {
  _id: string;
  _type: 'tablePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  h1?: string;
  tableData?: Array<
    {
      _key: string;
    } & CustomEventReference
  >;
};

export type CardInfoReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'cardInfo';
};

export type CardsPage = {
  _id: string;
  _type: 'cardsPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  h1?: string;
  subText?: string;
  infoCards?: Array<
    {
      _key: string;
    } & CardInfoReference
  >;
};

export type CardInfo = {
  _id: string;
  _type: 'cardInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  name?: string;
  shortDescription?: string;
  amount?: number;
  rating?: number;
};

export type ProjectInfo = {
  _id: string;
  _type: 'projectInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  projectName?: string;
  projectDescription?: string;
  content?: Array<string>;
};

export type DashboardPage = {
  _id: string;
  _type: 'dashboardPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  h1?: string;
  subText?: string;
  detailInfo?: Array<string>;
  cardsTitle?: string;
};

export type ProjectInfoReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'projectInfo';
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  infoSection?: {
    slug?: Slug;
    linkedinLink?: string;
    avatar?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    bgImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    username?: string;
    jobTitle?: string;
    location?: string;
    status?: string;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    experience?: Array<{
      slug?: Slug;
      name?: string;
      description?: string;
      logo?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      };
      _type: 'job';
      _key: string;
    }>;
  };
  aboutSection?: {
    slug?: Slug;
    descriptionLeft?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    descriptionRight?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    technologies?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }>;
  };
  experienceSection?: {
    slug?: Slug;
    projects?: Array<
      {
        _key: string;
      } & ProjectInfoReference
    >;
    companies?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }>;
  };
  educationSection?: {
    slug?: Slug;
    link?: string;
    logo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    h3?: string;
    details?: string;
    summary?: string;
  };
  contactSection?: {
    slug?: Slug;
    mainText?: string;
    additionalText?: string;
    locationText?: string;
    phoneNumber?: string;
    email?: string;
    linkedinLink?: string;
    githubLink?: string;
    telegramLink?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CatImageReference
  | GalleryPage
  | SanityImageAssetReference
  | CatImage
  | SanityImageCrop
  | SanityImageHotspot
  | ContactPage
  | Slug
  | AboutPage
  | CustomEvent
  | CustomEventReference
  | TablePage
  | CardInfoReference
  | CardsPage
  | CardInfo
  | ProjectInfo
  | DashboardPage
  | ProjectInfoReference
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/app/(app-home)/(public-info)/contact-us/page.tsx
// Variable: contactPageQuery
// Query: *[_type=="contactPage"][0]{content}
export type ContactPageQueryResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
} | null;

// Source: ../web/src/app/(app-home)/(public-info)/terms/page.tsx
// Variable: getAboutPageContent
// Query: *[_type=="aboutPage"][0]{content}
export type GetAboutPageContentResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
} | null;

// Source: ../web/src/app/(app-home)/about/page.tsx
// Variable: getAboutPageQuery
// Query: *[_type=="homePage"][0]{   infoSection {    username,    linkedinLink,    jobTitle,    location,    status,    description,    experience[] {      name,      description,      "logo": logo.asset->url    },    "avatar": avatar.asset->url,    "background": bgImage.asset->url  },  aboutSection {    slug,    descriptionLeft,    descriptionRight,    "technologies": technologies[].asset->url  }}
export type GetAboutPageQueryResult = {
  infoSection: {
    username: string | null;
    linkedinLink: string | null;
    jobTitle: string | null;
    location: string | null;
    status: string | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    experience: Array<{
      name: string | null;
      description: string | null;
      logo: string | null;
    }> | null;
    avatar: string | null;
    background: string | null;
  } | null;
  aboutSection: {
    slug: Slug | null;
    descriptionLeft: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    descriptionRight: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    technologies: Array<string | null> | null;
  } | null;
} | null;

// Source: ../web/src/app/(app-home)/contact/page.tsx
// Variable: getContactPageQuery
// Query: *[_type=="homePage"][0]{   contactSection {    ...  },}
export type GetContactPageQueryResult = {
  contactSection: {
    slug?: Slug;
    mainText?: string;
    additionalText?: string;
    locationText?: string;
    phoneNumber?: string;
    email?: string;
    linkedinLink?: string;
    githubLink?: string;
    telegramLink?: string;
  } | null;
} | null;

// Source: ../web/src/app/(app-home)/experience/page.tsx
// Variable: getExperiencePageQuery
// Query: *[_type=="homePage"][0]{   experienceSection {    slug,    "companies": companies[].asset->url,    projects[]->{      projectName,      projectDescription,      content    }  },  educationSection {    ...,    "logo": logo.asset->url,    }}
export type GetExperiencePageQueryResult = {
  experienceSection: {
    slug: Slug | null;
    companies: Array<string | null> | null;
    projects: Array<{
      projectName: string | null;
      projectDescription: string | null;
      content: Array<string> | null;
    }> | null;
  } | null;
  educationSection: {
    slug?: Slug;
    link?: string;
    logo: string | null;
    h3?: string;
    details?: string;
    summary?: string;
  } | null;
} | null;

// Source: ../web/src/app/(app-home)/page.tsx
// Variable: getHomePageQuery
// Query: *[_type=="homePage"][0]{  ...,  infoSection{    username,    linkedinLink,    jobTitle,    location,    status,    description,    experience[] {      name,      description,      "logo": logo.asset->url    },    "avatar": avatar.asset->url,    "background": bgImage.asset->url  },  aboutSection {  slug,   descriptionLeft,    descriptionRight,    "technologies": technologies[].asset->url  },  experienceSection {    slug,    "companies": companies[].asset->url,    projects[]->{      projectName,      projectDescription,      content    }  },  educationSection {    ...,    "logo": logo.asset->url,    }}
export type GetHomePageQueryResult = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  infoSection: {
    username: string | null;
    linkedinLink: string | null;
    jobTitle: string | null;
    location: string | null;
    status: string | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    experience: Array<{
      name: string | null;
      description: string | null;
      logo: string | null;
    }> | null;
    avatar: string | null;
    background: string | null;
  } | null;
  aboutSection: {
    slug: Slug | null;
    descriptionLeft: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    descriptionRight: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    technologies: Array<string | null> | null;
  } | null;
  experienceSection: {
    slug: Slug | null;
    companies: Array<string | null> | null;
    projects: Array<{
      projectName: string | null;
      projectDescription: string | null;
      content: Array<string> | null;
    }> | null;
  } | null;
  educationSection: {
    slug?: Slug;
    link?: string;
    logo: string | null;
    h3?: string;
    details?: string;
    summary?: string;
  } | null;
  contactSection?: {
    slug?: Slug;
    mainText?: string;
    additionalText?: string;
    locationText?: string;
    phoneNumber?: string;
    email?: string;
    linkedinLink?: string;
    githubLink?: string;
    telegramLink?: string;
  };
} | null;

// Source: ../web/src/app/dashboard/courses/[slug]/page.tsx
// Variable: getCardPageQuery
// Query: *[_type == "cardInfo" && slug.current == $cardSlug][0]{   name,   shortDescription,   amount,   rating,}
export type GetCardPageQueryResult = {
  name: string | null;
  shortDescription: string | null;
  amount: number | null;
  rating: number | null;
} | null;

// Source: ../web/src/app/dashboard/courses/page.tsx
// Variable: getCardsPageDataQuery
// Query: *[_type=="cardsPage"][0]{ h1, subText, "infoCards": infoCards[]->{   name,   shortDescription,   amount,   rating,   "slug": slug.current, }}
export type GetCardsPageDataQueryResult = {
  h1: string | null;
  subText: string | null;
  infoCards: Array<{
    name: string | null;
    shortDescription: string | null;
    amount: number | null;
    rating: number | null;
    slug: string | null;
  }> | null;
} | null;

// Source: ../web/src/app/dashboard/events/page.tsx
// Variable: totalCountQuery
// Query: count(*[    _type == "customEvent" &&    (      $search == "*" ||      name match $search + "*" ||      description match $search + "*"    )  ])
export type TotalCountQueryResult = number;

// Source: ../web/src/components/dashboard/events-table/table.tsx
// Variable: getCustomEventsQuery
// Query: *[_type == "customEvent" &&    (      $search == "*" ||      name match $search + "*" ||      description match $search + "*"    )][$start...$end]{    "slug": slug.current,    name,    description,    startDate,    endDate,    categories,    status,    type,}
export type GetCustomEventsQueryResult = Array<{
  slug: string | null;
  name: string | null;
  description: string | null;
  startDate: string | null;
  endDate: string | null;
  categories: Array<'Development' | 'Marketing'> | null;
  status: 'approved' | 'inProgress' | null;
  type: 'external' | 'internal' | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type=="contactPage"][0]{\ncontent\n}': ContactPageQueryResult;
    '*[_type=="aboutPage"][0]{\ncontent\n}': GetAboutPageContentResult;
    '*[_type=="homePage"][0]{\n   infoSection {\n    username,\n    linkedinLink,\n    jobTitle,\n    location,\n    status,\n    description,\n    experience[] {\n      name,\n      description,\n      "logo": logo.asset->url\n    },\n    "avatar": avatar.asset->url,\n    "background": bgImage.asset->url\n  },\n  aboutSection {\n    slug,\n    descriptionLeft,\n    descriptionRight,\n    "technologies": technologies[].asset->url\n  }\n}': GetAboutPageQueryResult;
    '*[_type=="homePage"][0]{\n   contactSection {\n    ...\n  },\n}': GetContactPageQueryResult;
    '*[_type=="homePage"][0]{\n   experienceSection {\n    slug,\n    "companies": companies[].asset->url,\n    projects[]->{\n      projectName,\n      projectDescription,\n      content\n    }\n  },\n  educationSection {\n    ...,\n    "logo": logo.asset->url,  \n  }\n}': GetExperiencePageQueryResult;
    '*[_type=="homePage"][0]{\n  ...,\n  infoSection{\n    username,\n    linkedinLink,\n    jobTitle,\n    location,\n    status,\n    description,\n    experience[] {\n      name,\n      description,\n      "logo": logo.asset->url\n    },\n    "avatar": avatar.asset->url,\n    "background": bgImage.asset->url\n  },\n  aboutSection {\n  slug,\n   descriptionLeft,\n    descriptionRight,\n    "technologies": technologies[].asset->url\n  },\n  experienceSection {\n    slug,\n    "companies": companies[].asset->url,\n    projects[]->{\n      projectName,\n      projectDescription,\n      content\n    }\n  },\n  educationSection {\n    ...,\n    "logo": logo.asset->url,  \n  }\n}': GetHomePageQueryResult;
    '*[_type == "cardInfo" && slug.current == $cardSlug][0]{\n   name,\n   shortDescription,\n   amount,\n   rating,\n}': GetCardPageQueryResult;
    '*[_type=="cardsPage"][0]{\n h1,\n subText,\n "infoCards": infoCards[]->{\n   name,\n   shortDescription,\n   amount,\n   rating,\n   "slug": slug.current,\n }\n}\n': GetCardsPageDataQueryResult;
    'count(*[\n    _type == "customEvent" &&\n    (\n      $search == "*" ||\n      name match $search + "*" ||\n      description match $search + "*"\n    )\n  ])': TotalCountQueryResult;
    '*[_type == "customEvent" &&\n    (\n      $search == "*" ||\n      name match $search + "*" ||\n      description match $search + "*"\n    )][$start...$end]{\n    "slug": slug.current,\n    name,\n    description,\n    startDate,\n    endDate,\n    categories,\n    status,\n    type,\n}\n': GetCustomEventsQueryResult;
  }
}
